### ISSUE TITLE
[Feature] Not able to use large clipboard over Alacritty

### ISSUE THREAD

**Issue by ztlevi** [spudlyo/clipetty#14]
**Describe the feature**
It seems like copying fails if I try to copy over large number of lines, e.g. 100 lines. So I guess larger clipboard feature is not implemented for Alacritty.

According to the disscussion over here https://github.com/alacritty/alacritty/issues/600. Large clipboard is supported in Alacritty. Would you mind take a look at it and see if we are able to support it?

Thanks!

**To Reproduce**
Basic copying steps.

**Expected behavior**

** System Info (please complete the following information):**
 - OS: Use mac ssh into linux
 - Emacs Version: 26.3
 - Terminal program: Alacritty
 - Any terminal multiplexers in play: Tmux
 - Local or remote: over SSH

**Additional context**

**Comment by Shooooooooo** [comment]
Just want to say thanks to bring this up as I am facing the same issue.

**Comment by spudlyo** [comment]
Hi there,

From reading the linked issue in alacritty/alacritty#600, it's not clear to me _how_ they get around the OSC message length limitation to support large pastes. Alacritty doesn't seem like they use the same protocol extension that Kitty does.  Can you try to paste something that is around 74,000 bytes and let me know if that works with Alacritty, because that _should_ work.

**Comment by ztlevi** [comment]
Copying and pasting large bytes in pure terminal does work. I'm not 100 sure what you want me to test, in emacs or just terminal?

**Comment by spudlyo** [comment]
Sorry, I misspoke, I said 'paste' when I meant 'copy'. This gets to your bug, you wrote:
> It seems like copying fails if I try to copy over large number of lines, e.g. 100 lines.

I was trying to figure out the maximum size of something you could _copy_ with Clipetty using Alacritty.

**Comment by spudlyo** [comment]
By the way, this limitation is fixed in Alacritty version 0.4.2-dev and above. If you can upgrade, this should be fixed for you.

**Comment by ztlevi** [comment]
@spudlyo Yes, I can confirm [alacritty 0.4.2 rc4](https://github.com/alacritty/alacritty/releases/tag/v0.4.2-rc4) supports large clipboard. It just works out of box. 

Thanks for the great help and amazing package!

**Comment by spudlyo** [comment]
README updated, thanks for your report!
