### ISSUE TITLE
[BUG] Clipetty permission denided /dev/pts/3

### ISSUE THREAD

**Issue by ztlevi** [spudlyo/clipetty#15]
**Describe the bug**
On my company's desktop, there is a admin user controlled by my company called bobby.mcgee monitors users. /dev/pts/3 belongs to that user.

When I try to use clipetty, it pops 
```
clipetty--emit: Opening output file: Permission denied, /dev/pts/3
```
Can we skip those output files does not belongs to the current user?

> Notes: It probly will happen if two people ssh into a same machine.

**To Reproduce**
1. Maybe create a file belongs to another admin user.
2. ssh and use clipetty

**Expected behavior**
No permission error.

** System Info (please complete the following information):**
 - OS: LInux
 - Emacs Version: 26.3
 - Terminal program: Alacritty
 - Any terminal multiplexers in play: Tmux
 - Local or remote (over SSH)

**Additional context**

**Comment by spudlyo** [comment]
Hi there,

Can you try adding the following to your `.tmux.conf` file?

```
set -ag update-environment "SSH_TTY"
```

Once you do that, detach your tmux session, log off, log back in, and then attach to your tmux session. I _think_ that should fix it.
