### ISSUE TITLE
How to enable Clipetty in Doom Emacs?

### ISSUE THREAD

**Issue by whjiang** [spudlyo/clipetty#19]
I am not familiar with elisp. Can you tell me how to configure Doom Emacs to make Clipetty work?

Thanks a lot!

**Comment by spudlyo** [comment]
Hi there,

There is a good chance that Clipetty will be added to Doom Emacs shortly, and you won't have to make any manual customizations to make it work. Keep an eye on hlissner/doom-emacs/issues/2671 for more details.

**Comment by whjiang** [comment]
Thanks a lot for the update.

Sent from my iPhone

在 2020年4月1日，上午12:26，Mike Hamrick <notifications@github.com> 写道：

﻿

Hi there,

There is a good chance that Clipetty will be added to Doom Emacs shortly, and you won't have to make any manual customizations to make it work. Keep an eye on hlissner/doom-emacs/issues/2671<https://github.com/hlissner/doom-emacs/issues/2671> for more details.

**Comment by hlissner** [comment]
hlissner/doom-emacs#2671 was merged a short while ago and is now enabled in tty Emacs by default. No extra steps required, so you may consider this issue resolved.

**Comment by whjiang** [comment]
I updated to newest Doom and following code (not sure it is necessary or not)
``` lisp
(after! clipetty
	(when (not (display-graphic-p))
	  (global-clipetty-mode)
	  )
	)
```

I use ITerm2 and ssh to a machine, the copy function in terminal Emacs works perfectly.

**Comment by hlissner** [comment]
@whjiang It isn't necessary. [Doom activates it for you](https://github.com/hlissner/doom-emacs/blob/develop/core/core-editor.el#L172-L173).

**Comment by whjiang** [comment]
> @whjiang It isn't necessary. [Doom activates it for you](https://github.com/hlissner/doom-emacs/blob/develop/core/core-editor.el#L172-L173).

Thanks a lot for the clarification.
