### ISSUE TITLE
Can't copy long text on Kitty

### ISSUE THREAD

**Issue by toyboot4e** [spudlyo/clipetty#23]
I couldn't copy long text on Kitty, while I could do on iTerm.
Is this related to #1? (Clipetty does not fully support Kitty's extended OSC 52 xterm protocol)

Example:

```sh
$ seq 0 10000 > long-file
$ emacs -nw long-file
$ # try to copy the whole buffer with `clipetty-kill-ring-save`
```

Thank you.

**Comment by spudlyo** [comment]
This is indeed a bug. It worked for me on iTerm2 and when I tried it in Kitty, it ended up spewing a bunch of garbage to my terminal and didn't put anything into the OS clipboard.

**Comment by toyboot4e** [comment]
Oh looks like already solved! (Thanks to Kitty update?)

`clipetty` is super comfortable, thanks ;)
